services:
  mongodb:
    container_name: mongo-service
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  backend:
    container_name: backend
    image: manishvishwa801/wanderlust-backend-beta:latest
    env_file:
      - ./backend.env
    ports:
      - "31100:8080"
    depends_on:
      - mongodb
    restart: always

  frontend:
    container_name: frontend
    image: manishvishwa801/wanderlust-frontend-beta:latest
    env_file:
      - ./frontend.env
    ports:
      - "5173:5173"
    restart: always

  redis:
    container_name: redis-service
    restart: always
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  mongo_data:    # data persists even after docker compose down
